# Site settings
title: IXZV
description: "blog"
url:  "https://tladudtn.github.io" # Actual base url of the website
baseurl: ""           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "tladudtn"
  email: "tladudtn7598@gmail.com"
  url: "https://tladudtn.github.io"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

logo: /assets/img/logo.png
webmaster_verifications:
  google: 
lang: ko_Kr

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never